from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1291, 731)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1301, 731))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 1291, 731))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/work_space.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1291, 731))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame_2.setEnabled(True)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setStyleSheet("background-color: rgb(80, 80, 80);\n"
"border-bottom: 3px solid black;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1291, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_13 = QtWidgets.QFrame(parent=self.horizontalLayoutWidget_2)
        self.frame_13.setMinimumSize(QtCore.QSize(822, 0))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 600))
        self.frame_13.setStyleSheet("background-color: transparent;\n"
"border-color: transparent;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 401, 48))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(parent=self.horizontalLayoutWidget_2)
        self.frame_14.setMinimumSize(QtCore.QSize(225, 0))
        self.frame_14.setStyleSheet("background-color: transparent;\n"
"border-color: transparent;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.comboBox = QtWidgets.QComboBox(parent=self.frame_14)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 211, 31))
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(16777213, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox.setStyleSheet("color: black;\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_15.setGeometry(QtCore.QRect(12, 12, 190, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_15.setFont(font)
        self.frame_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_3.setGeometry(QtCore.QRect(3, 5, 181, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.frame_14)
        self.frame_12 = QtWidgets.QFrame(parent=self.horizontalLayoutWidget_2)
        self.frame_12.setStyleSheet("background-color: transparent;\n"
"border-color: transparent;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.screenshot_button = QtWidgets.QPushButton(parent=self.frame_12)
        self.screenshot_button.setGeometry(QtCore.QRect(10, 14, 101, 26))
        self.screenshot_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.screenshot_button.setStyleSheet("background-color: transparent;")
        self.screenshot_button.setText("")
        self.screenshot_button.setObjectName("screenshot_button")
        self.horizontalLayout_2.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(parent=self.horizontalLayoutWidget_2)
        self.frame_11.setStyleSheet("background-color: transparent;\n"
"border-color: transparent;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_13.setGeometry(QtCore.QRect(30, 10, 31, 31))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("img/5972622.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_14.setGeometry(QtCore.QRect(70, 5, 41, 41))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("img/7546863-no-bg-preview (carve.photos).png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.min_button = QtWidgets.QPushButton(parent=self.frame_11)
        self.min_button.setGeometry(QtCore.QRect(30, 10, 31, 31))
        self.min_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.min_button.setStyleSheet("background-color: transparent;")
        self.min_button.setText("")
        self.min_button.setObjectName("min_button")
        self.close_button = QtWidgets.QPushButton(parent=self.frame_11)
        self.close_button.setGeometry(QtCore.QRect(75, 10, 31, 31))
        self.close_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.close_button.setStyleSheet("background-color: transparent;")
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.frame_11)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.frame_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1291, 681))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5 = QtWidgets.QFrame(parent=self.horizontalLayoutWidget)
        self.frame_5.setMaximumSize(QtCore.QSize(201, 16777215))
        self.frame_5.setStyleSheet("background-color: rgba(139, 139, 139, 100);\n"
"border-right: 2px solid black;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame_5)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 201, 681))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(parent=self.verticalLayoutWidget_2)
        self.frame_6.setStyleSheet("background-color: transparent;\n"
"border-color: transparent;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.frame_6)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 201, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.label_6.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_10 = QtWidgets.QFrame(parent=self.verticalLayoutWidget_2)
        self.frame_10.setStyleSheet("background-color: transparent;\n"
"border-color: transparent;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=self.frame_10)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 201, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        self.label_7.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_7.setStyleSheet("color: white;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(parent=self.verticalLayoutWidget_2)
        self.frame_9.setStyleSheet("background-color: transparent;\n"
"border-color: transparent;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(parent=self.frame_9)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 201, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_5)
        self.label_9.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_9.setStyleSheet("color: white;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_7 = QtWidgets.QFrame(parent=self.verticalLayoutWidget_2)
        self.frame_7.setStyleSheet("background-color: transparent;\n"
"border-color: transparent;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(parent=self.frame_7)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 201, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_6)
        self.label_11.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_11.setStyleSheet("color: white;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(parent=self.verticalLayoutWidget_2)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 450))
        self.frame_8.setStyleSheet("background-color: transparent;\n"
"border-color: transparent;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_2.addWidget(self.frame_8)
        self.horizontalLayout.addWidget(self.frame_5)
        self.work_place = QtWidgets.QFrame(parent=self.horizontalLayoutWidget)
        self.work_place.setStyleSheet("")
        self.work_place.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.work_place.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.work_place.setObjectName("work_place")
        self.horizontalLayout.addWidget(self.work_place)
        self.verticalLayout.addWidget(self.frame_3)
        self.notification_frame = QtWidgets.QFrame(parent=self.frame)
        self.notification_frame.setGeometry(QtCore.QRect(963, 641, 321, 81))
        self.notification_frame.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"border-radius: 16px;")
        self.notification_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.notification_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.notification_frame.setObjectName("notification_frame")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.notification_frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(13, 5, 293, 68))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.notification_frame.raise_()
        self.label.raise_()
        self.verticalLayoutWidget.raise_()

        self.retranslateUi(Form)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Graph Editor"))
        self.comboBox.setCurrentText(_translate("Form", "Поиск в ширину"))
        self.comboBox.setItemText(0, _translate("Form", "Поиск в ширину"))
        self.comboBox.setItemText(1, _translate("Form", "Поиск в глубину"))
        self.label_3.setText(_translate("Form", "Алгоритмы"))
        self.label_4.setText(_translate("Form", "Скриншот"))
        self.label_6.setText(_translate("Form", "Рисунок"))
        self.label_5.setText(_translate("Form", "Добавить вершину"))
        self.label_7.setText(_translate("Form", "Рисунок"))
        self.label_8.setText(_translate("Form", "Добавить ребро"))
        self.label_9.setText(_translate("Form", "Рисунок"))
        self.label_10.setText(_translate("Form", "Добавить дугу"))
        self.label_11.setText(_translate("Form", "Рисунок"))
        self.label_12.setText(_translate("Form", "Добавить вершину"))
